### ISSUE TITLE
MATLAB_INCLUDE_DIR-NOTFOUND

### ISSUE THREAD

**Issue by rustycandlewick** [BjoernHaefner/MumfordShahCuda#2]
Hi,

I am trying to use this on a ubuntu environment in order to use the DepthSRFromShading repo. However, I continually am unable to use the mumfordShahMEX function since cmake gives the error above and it is unable to build the mumfordShahMEX.h file. Is there a way to fix this?

**Comment by BjoernHaefner** [comment]
Hey,
What were your steps of action to build MumfordShahCuda code?

**Comment by rustycandlewick** [comment]
Hi, thanks for the reply! I just figured out the problem was the MATLAB directory path is written differently. Instead of '/matlab-r2018a' it is actually just '/r2021a'. I included 'matlab-'  so it couldn't find the directory.
